version: '3.4'
networks:
  backend:
services:
  customerdb:
    container_name: customers-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=password@12345#
    networks:
        - backend
    ports:
       - 18001:1433 

  customerwebapi:
    container_name: customers-api
    image: ${DOCKER_REGISTRY-}customerwebapi
    build:
      context: .
      dockerfile: CustomerWebApi/Dockerfile
    networks:
        - backend
    environment:
        - DB_HOST=customerdb
        - DB_NAME=customer
        - DB_SA_PASSWORD=password@12345#

  productwebapi:
    container_name: product-api
    image: ${DOCKER_REGISTRY-}productwebapi
    build:
      context: .
      dockerfile: ProductWebApi/Dockerfile
    networks:
        - backend
    environment:
        - DB_HOST=productdb
        - DB_NAME=dms_product
        - DB_ROOT_PASSWORD=password@12345#

  productdb:
    container_name: product-db
    image: mysql:8.0.32-oracle
    environment:
        - MYSQL_ROOT_PASSWORD=password@12345#
    ports:
        - 18003:3306
    networks:
        - backend

  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile
    ports:
       - 8001:80
    networks:
        - backend